name: pum-26
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy<2
  - scipy
  - pandas
  - scikit-learn=1.2.1
  - matplotlib
  - seaborn
  - bokeh>=3.0.3
  - rdkit
  - openbabel
  - jupyter
  - notebook
  - pyyaml
  - tqdm
  - streamlit
  - wandb
  - gh
  - black
  - isort
  - pytest
  - pip:
      - torch==2.2.2
      - torch_geometric
      - pytdc
